# Generated by Django 3.2.7 on 2021-10-02 11:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('service', models.CharField(choices=[('None', 'Select Type Of Service'), ('Android Apps', 'Android Apps'), ('Website Development', 'Website Development'), ('Networking', 'Networking')], default=' ', max_length=100, null=True)),
                ('project_dec', models.CharField(max_length=400, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
